baseURL = "https://kelisbu.github.io/"
languageCode = "en-us"
title = "Ke Li"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false
  customCSS = ["css/custom.css"]
[menu]
  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "CV"
    url = "/cv.pdf"
    weight = 2

[params]

  [params.profileMode]
    enabled = true
    title = "Ke Li"
    subtitle = "Ph.D. student at Stony Brook University"
    imageUrl = "/img/me.jpg"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:keli.1@stonybrook.edu"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/KELISBU"

  [[params.socialIcons]]
    name = "googlescholar"
    url = "https://scholar.google.com/citations?user=jJURvasAAAAJ&hl=en"

  [[params.socialIcons]]
    name = "cv"
    url = "/cv.pdf"
